### ISSUE TITLE
Could we get features for THUMOS'14?

### ISSUE THREAD

**Issue by JingweiJ** [wzmsltw/BSN-boundary-sensitive-network#13]
Hi Tianwei,

Thanks for your great work! Could we also have extracted features of THUMOS'14? It would be great if the rescaled and original features for THUMOS'14 are provided. Thank you so much!

**Comment by wzmsltw** [comment]
Hi Jingwei, sorry for the delay. I have upload features of THUMOS14 in BaiduYun. Notice that for THUMOS14, we do not rescale feature since the feature sequence is too long. Instead, sliding window is used on THUMOS-14. You can read paper for more detail.

链接:https://pan.baidu.com/s/1Vj5WITTC8OqrEgJVrZnkKA 
密码:amjm

**Comment by JingweiJ** [comment]
Hi Tianwei, thanks for you quick response. However, the name of compressed file is "feature_anet_200.zip". Are they features of activity net or THUMOS14?

**Comment by wzmsltw** [comment]
Hi Jingwei. This is the feature of THUMOS14, which is extracted using models pre-trained on ActivityNet.

**Comment by JingweiJ** [comment]
Thanks! Still, I only find 413 csv files each in rgb and flow folder from the BaiduYun link, while the number of test and validation videos together is 1574+1010=2584. Are there some files missing?

**Comment by wzmsltw** [comment]
In THUMOS-14, only 200 (validation) + 213 (testing) = 413 videos are temporally annotated, thus I only extract features for these videos.
