### ISSUE TITLE
Issue regarding rescaling the feature length

### ISSUE THREAD

**Issue by samxuxiang** [wzmsltw/BSN-boundary-sensitive-network#8]
Hi, 

(1) You mentioned that "**For convenience of training and testing, we rescale the feature length of all videos to same length 100**", if I understand correctly, this means that you only extract 100 snippets per video clip? Also would you mind elaborating on how the video resizing is done? 

(2) Also there are many improvements for the winning solution compared to BSN baseline, will you consider releasing the code for the winning solution? 

Thank you

**Comment by wzmsltw** [comment]
Hi @samxuxiang 
(1) I extract feature for each 16 frames ( a snippet) and get feature sequence with uncertain length, than I rescale the featue sequence to 100.  And I had provide reference code in data/activitynet_feature_cuhk/data_process.py

(2) Since the anet-18 solution is emsembled by many results, and I have deleted many intermediate results.  So I am not planning to release codes of anet-18 solution. You can refer our report for our improvements.
